name: CD
'on':
  push:
    branches:
    - main
    - dev
    - qa
    - prod
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Dev
      run: echo 'Deploying to Dev environment'
  deploy-qa:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to QA
      run: echo 'Deploying to QA environment'
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Prod
      run: echo 'Deploying to Prod environment'
